openapi: '3.0.0'
info:
  title: IntelliQ-BE API
  description: API Documentation for IntelliQ-BE services.
  version: '3.1.2'

servers:
  - url: https://intelliq-be-s1.azurewebsites.net/
    description: Production
  - url: https://intelliq-be-s2.azurewebsites.net
    description: Testing
  - url: http://localhost:3000/
    description: Development

tags:
  - name: General
    description: General APIs
  - name: User
    description: APIs related to user management
  - name: Quizzes
    description: APIs related to quiz management

paths:
  /api/welcome:
    get:
      tags: [General]
      summary: Retrieve Welcome Message
      responses:
        '200':
          description: Success
          content:
            text/plain:
              example: "Welcome to the IntelliQ-BE API! For Documentation please visit: intelliq-be.azurewebsites.net/api-docs/"

  /api/signup:
    post:
      tags: [User]
      summary: Register New User
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: New user's email
                password:
                  type: string
                  description: New user's password
            example:
              email: newUser@user.com
              password: newPassword
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userID:
                    type: string
                  email:
                    type: string
        '400':
          description: User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/login:
    post:
      tags: [ User ]
      summary: User Sign-in
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Existing user's email
                password:
                  type: string
                  description: Existing user's password
              required:
                - email
                - password
              example:
                email: newUser@user.com
                password: newPassword
      responses:
        '200':
          description: User signed in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userID:
                    type: string
                  email:
                    type: string
        '400':
          description: Invalid login credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/logout:
    post:
      tags: [ User ]
      summary: User Sign-out
      operationId: logoutUser
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: User signed out successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Invalid login credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/auth/google:
    get:
      tags: [ User ]
      summary: Google Sign-in
      operationId: googleLoginUser
      responses:
        '200':
          description: User signed in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userID:
                    type: string
                  email:
                    type: string
        '400':
          description: Invalid login credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/auth/google/callback:
    get:
      tags: [ User ]
      summary: Google Sign-in Callback
      operationId: googleLoginUserCallback
      responses:
        '200':
          description: User signed in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userID:
                    type: string
                  email:
                    type: string
        '400':
          description: Invalid login credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/auth/userSession:
    get:
      tags: [ User ]
      summary: Get User Session
      operationId: getUserSession
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: User session retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userID:
                    type: string
                  email:
                    type: string
        '400':
          description: Invalid login credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/quiz:
    get:
      tags: [ Quizzes ]
      summary: Retrieve Custom Quiz
      security:
        - BearerAuth: [ ]
      parameters:
        - name: numberOfQuestions
          in: query
          required: true
          schema:
            type: integer
        - name: interests
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Custom quiz retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  rawQuestions:
                    type: array
                    items:
                      type: object
                      properties:
                        quizTitle:
                          type: string
                        questions:
                          type: array
                          items:
                            type: object
                            properties:
                              questionTitle:
                                type: string
                              text:
                                type: string
                              options:
                                type: array
                                items:
                                  type: string
                              correctAnswer:
                                type: string
        '400':
          description: Invalid question format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Not Authorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '403':
          description: Must be signed in
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Failed to create quiz / Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/submit-quiz:
    post:
      tags: [ Quizzes ]
      summary: Submit Custom Quiz
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rawQuestions:
                  type: object
                  properties:
                    quizTitle:
                      type: string
                    questions:
                      type: array
                      items:
                        type: object
                        properties:
                          text:
                            type: string
                          options:
                            type: array
                            items:
                              type: string
                          correctAnswer:
                            type: string
                          userAnswer:
                            type: string
                    timeTaken:
                      type: integer
      responses:
        '200':
          description: Quiz submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  quiz_id:
                    type: string
                  rawQuestions:
                    type: object
                    properties:
                      quiz_title:
                        type: string
                      timeTaken:
                        type: integer
                      correctAnswersCount:
                        type: integer
                      questions:
                        type: array
                        items:
                          type: object
                          properties:
                            text:
                              type: string
                            correctAnswer:
                              type: string
                            userAnswer:
                              type: string
        '400':
          description: Invalid question format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Not Authorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '403':
          description: Must be signed in
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Failed to create quiz / Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /quizzes:
    get:
      tags: [ History ]
      summary: Retrieve All Quizzes
      security:
        - BearerAuth: [ ]
      parameters:
        - name: offset
          in: query
          required: true
          schema:
            type: integer
        - name: limit
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Quizzes retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  quizzes:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        quiz_title:
                          type: string
                        total_time_taken:
                          type: integer
        '400':
          description: Invalid question format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Not Authorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '403':
          description: Must be signed in
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Failed to create quiz / Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /quizzes/{quiz_id}:
    get:
      tags: [ History ]
      summary: Retrieve Quiz by ID
      security:
        - BearerAuth: [ ]
      parameters:
        - name: quiz_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Quiz retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  user_id:
                    type: string
                  quiz_title:
                    type: string
                  created_at:
                    type: string
                  total_time_taken:
                    type: integer
                  correct_answers_count:
                    type: integer
                  questions:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        quiz_id:
                          type: string
                        text:
                          type: string
                        options:
                          type: array
                          items:
                            type: string
                        correct_answer:
                          type: string
                        created_at:
                          type: string
                        user_responses:
                          type: array
                          items:
                            type: object
                            properties:
                              id:
                                type: string
                              question_id:
                                type: string
                              quiz_id:
                                type: string
                              user_answer:
                                type: string
                              is_correct:
                                type: boolean
                              created_at:
                                type: string

        '400':
          description: Invalid question format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Not Authorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '403':
          description: Must be signed in
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Failed to create quiz / Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    patch:
      tags: [ History ]
      summary: Delete Quiz by ID
      security:
        - BearerAuth: [ ]
      parameters:
        - name: quiz_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Quiz retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  user_id:
                    type: string
                  quiz_title:
                    type: string
                  created_at:
                    type: string
                  total_time_taken:
                    type: integer
                  correct_answers_count:
                    type: integer
        '500':
          description: Entry doesn't exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  error:
                    type: string

components:
  schemas:
    QuizSchema:
      type: object
      properties:
        questions:
          type: array
          items:
            type: object
            properties:
              text:
                type: string
              options:
                type: array
                items:
                  type: string
              correctAnswer:
                type: string
