openapi: '3.0.0'
info:
  title: IntelliQ-BE API
  description: API Documentation for IntelliQ-BE services.
  version: '3.1.2'

servers:
  - url: https://intelliq-be.azurewebsites.net/
    description: Production
  - url: http://localhost:3000/
    description: Development

tags:
  - name: General
    description: General APIs
  - name: User
    description: APIs related to user management
  - name: Quizzes
    description: APIs related to quiz management

paths:
  /api/welcome:
    get:
      tags: [General]
      summary: Retrieve Welcome Message
      responses:
        '200':
          description: Success
          content:
            text/plain:
              example: Welcome to the IntelliQ-BE API

  /api/signup:
    post:
      tags: [User]
      summary: Register New User
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: New user's email
                password:
                  type: string
                  description: New user's password
            example:
              email: newUser@user.com
              password: newPassword
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userID:
                    type: string
                  email:
                    type: string
                  sessionToken:
                    type: string
        '400':
          description: User already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/signin:
    post:
      tags: [ User ]
      summary: User Sign-in
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Existing user's email
                password:
                  type: string
                  description: Existing user's password
                provider:
                  type: string
                  description: Authentication provider (optional)
              required:
                - email
                - password
              example:
                email: existingUser@user.com
                password: existingPassword
                provider: 'google'
      responses:
        '200':
          description: User signed in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userID:
                    type: string
                  email:
                    type: string
                  sessionToken:
                    type: string
        '400':
          description: Invalid login credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/getUserSession:
    get:
      tags: [ User ]
      summary: Get User Session
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: User session retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userID:
                    type: string
                  email:
                    type: string
        '401':
          description: Not authorized, invalid token, no token provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/quiz:
    post:
      tags: [ Quizzes ]
      summary: Retrieve Custom Quiz
      security:
        - BearerAuth: [ ]
      parameters:
        - name: numberOfQuestions
          in: query
          required: true
          schema:
            type: integer
        - name: interests
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Custom quiz retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    questions:
                      type: array
                      items:
                        type: object
                        properties:
                          text:
                            type: string
                          options:
                            type: array
                            items:
                              type: string
                          correctAnswer:
                            type: string
        '400':
          description: Invalid question format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: Not Authorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '403':
          description: Must be signed in
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Failed to create quiz / Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/quiz/javascript:
    get:
      tags:
        - Quizzes
      summary: Retrieve a JavaScript Quiz
      responses:
        '200':
          description: Successful retrieval of JavaScript quiz
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizSchema'
        '400':
          description: Invalid question format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/quiz/agile:
    get:
      tags:
        - Quizzes
      summary: Retrieve an Agile Management Quiz
      responses:
        '200':
          description: Successful retrieval of Agile Management quiz
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizSchema'
        '400':
          description: Invalid question format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/quiz/gaming:
    get:
      tags:
        - Quizzes
      summary: Retrieve a Gaming Quiz
      responses:
        '200':
          description: Successful retrieval of Gaming quiz
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizSchema'
        '400':
          description: Invalid question format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/quiz/css:
    get:
      tags:
        - Quizzes
      summary: Retrieve a CSS Quiz
      responses:
        '200':
          description: Successful retrieval of CSS quiz
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizSchema'
        '400':
          description: Invalid question format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/quiz/formula-one:
    get:
      tags:
        - Quizzes
      summary: Retrieve a Formula One Quiz
      responses:
        '200':
          description: Successful retrieval of Formula One quiz
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizSchema'
        '400':
          description: Invalid question format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /api/quiz/anime:
    get:
      tags:
        - Quizzes
      summary: Retrieve an Anime Quiz
      responses:
        '200':
          description: Successful retrieval of Anime quiz
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuizSchema'
        '400':
          description: Invalid question format
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    QuizSchema:
      type: object
      properties:
        questions:
          type: array
          items:
            type: object
            properties:
              text:
                type: string
              options:
                type: array
                items:
                  type: string
              correctAnswer:
                type: string