name: Build and deploy Node.js app to Azure Web Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy_to_first_app:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
      - run: unzip release.zip
      - name: 'Deploy to Azure Web App - IntelliQ-BE-S1'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'IntelliQ-BE-S1'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F641C9E536F846BBBEAD850D1E8E5EF7 }}

  deploy_to_second_app:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-second-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
      - run: unzip release.zip
      - name: 'Deploy to Azure Web App - IntelliQ-BE'
        id: deploy-to-second-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'IntelliQ-BE'
          slot-name: 'production'
          package: .
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e24498ce0aea41ffa2d08302d5e8d3df }}
